---

- name: Installing and configuring Docker
  hosts: all
  become: yes
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Rancher Server
  hosts: "Rancher"
  become: yes
  roles:
    - { role: rancher, tags: ["rancher"] }

- name: Register Rancher Hosts
  hosts: "Agents"
  become: yes
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }
